### ISSUE TITLE
DateTimes are marked as being in local time, but are intended to be in UTC

### ISSUE THREAD

**Issue by SteveAlexander** [MaikuB/flutter_appauth#162] opened 2020-11-26 20:49 UTC
The value of `accessTokenExpirationDateTime` is constructed using `DateTime.fromMillisecondsSinceEpoch(timeInMs)`.

I think it's meant to represent a UTC datetime, so it should use `DateTime.fromMillisecondsSinceEpoch(timeInMs, isUtc: true)`.

This causes difficulty in understanding the API (is the DateTime local or UTC?), and also potential errors in converting the time to other datetime libraries.

The code is in `method_channel_flutter_appauth.dart`.

Documentation for DateTime: https://api.dart.dev/stable/2.10.4/dart-core/DateTime-class.html

**Comment by MaikuB** [comment] 2020-11-26 21:57
I don't see a strong reason being presented on why it should be in UTC, though I know it might be standard for other ecosystems. With regards to checking if it's in UTC or local, the same docs you linked to shows that there are properties for doing so.

The reason for making it local was also linked to UX/DX. The common use case for the expiration time would be to compare it with [`DateTime.now()`](https://api.dart.dev/stable/2.10.4/dart-core/DateTime/DateTime.now.html) to see if the token has expired. That method returns a date in local time so making expiration time be local makes it easier to compare since it would be consistent. If it needs to be presented then having it in local time also makes it easier as most applications would present information in local time. That `DateTime.now()` returns it in local time also suggest that within that it's possible the preference within the ecosystem. Doing a search would indicate a number of other plugins have done the same. These are some examples

-  https://github.com/FirebaseExtended/flutterfire/blob/322a6283b511975ee7b9b83b2a055e0c67ce885b/packages/firebase_remote_config/lib/src/remote_config.dart#L47
- https://github.com/FirebaseExtended/flutterfire/blob/ba7124b5a0b24b76587cfdb6bb36afcb2427d792/packages/firebase_auth/firebase_auth_platform_interface/lib/src/id_token_result.dart#L35
- https://github.com/FirebaseExtended/flutterfire/blob/0054034125de1b4dede7f17304fb72b5f07db701/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart#L46

Based on what I presented above, I see more reason to keep it in local time and be hesitant to change it to UTC

**Comment by SteveAlexander** [comment] 2020-11-26 22:14
Thanks for the awesomely detailed response! 👍 

I had written the bug report assuming that this was an oversight, rather than a deliberate design decision.

The principle I use when designing systems is to keep all times within the logical rules of the system in UTC, and convert from local to UTC at the edges of the system, as far towards the edges as possible. (Similar principles for converting from encoded bytes into strings, etc.) The reasons for this are pretty compelling in server software, but less well explored for mobile apps.

I'd argue that following this principle in mobile apps for datetimes avoids the "once a year" issues around DST changes, as well as inconsistencies when a user changes timezone through travel (often more than once a year, at least when in more normal non-covid times).

But, I also think your design decision is a valid approach, and perhaps it is a simpler developer experience for many cases. For my own case, as I need to deal with timezone changes, and following my own app development principles, I expect I'll be converting the local datetimes from flutter_appauth into timemachine representations to use / store / calculate with (https://pub.dev/packages/time_machine).

**Comment by MaikuB** [comment] 2020-11-26 22:33
I normally go with UTC as well when it comes to .NET development (which I've done more of) as it's far more flexible and causes less problems. Unfortunately, Dart's date/time APIs aren't as fully featured, which likely explains why the ecosystem seems to  have gone with local time as there isn't even an API to get the current time in UTC

A package you might also want to consider is https://pub.dev/packages/timezone given a Googler is listed as one of the authors

**Comment by MaikuB** [comment] 2020-11-27 07:26
Will close this now since it's been confirmed that this was a design decision. If the ecosystem changes then happy to revisit this when that happens

**Closed by MaikuB** 2020-11-27 07:26 UTC
