### ISSUE TITLE
Receiving this error Minimum supported Gradle version is 5.6.4. Current version is 5.6.2

### ISSUE THREAD

**Issue by morrowyn** [MaikuB/flutter_appauth#183] opened 2021-02-09 17:33 UTC
I use the following:

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 9b2d32b605 (3 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5 

android build.gradle:
minSdkVersion 18
targetSdkVersion 30

pubspec.yaml:
flutter_appauth: ^0.9.2+6

Upon building with gradle I receive the following error.

A problem occurred evaluating root project 'flutter_appauth'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in E:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_appauth-0.9.2+6\android\gradle\wrapper\gradle-wrapper.properties to gradl
e-5.6.4-all.zip

When I manually edit the gradle-wrapper.properties inside the plugin directory, The error disappears.

**Comment by MaikuB** [comment] 2021-02-12 21:15
Can you provide a link to a repository that can reproduce this problem? Note that if you look at the plugin's folders here on GitHub, it doesn't have a gradle-wrapper.properties file aswell

**Comment by MaikuB** [comment] 2021-03-27 23:58
Closing due to lack of further response to getting info that can reproduce the issue

**Closed by MaikuB** 2021-03-27 23:58 UTC
