### ISSUE TITLE
Token Method

### ISSUE THREAD

**Issue by iTEEECH** [MaikuB/flutter_appauth#250] opened 2021-10-21 12:57 UTC
Hi,

I started to use your module which for me seems the best in oauth2 on Flutter but I encounter a problem. I initialized the "Authorize" method to get the "code" and the "code_verifier". 

So far everything works but once the token request is made, I have no answer because flutter_appauth not working if HTTP endpoint token uses Post' (client uses HTTP POST parameters), only Basic' (client uses HTTP Basic).

Maybe a future feature ?

Thank you

**Comment by MaikuB** [comment] 2021-11-02 09:15
Having trouble understanding what you're trying to communicate and not sure you have actually tracked down your problems correctly. This library already works with a number of identity providers like Azure AD where tokens are obtained by issue a POST request to a `token` endpoint and supports basic authentication provided you give it a client secret (e.g. see https://github.com/MaikuB/flutter_appauth/blob/2307f7cfadc3ce1d852c5d7140d98ed62302b086/flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java#L356). 

If there's something missing that you're having trouble communicating across then you will most likely need to look at submitting a PR

**Comment by MaikuB** [comment] 2021-11-14 06:12
Closing as the issue isn't clear and info seems incorrect. Feel free to re-open if you articulate the problem more clearly and provided evidence of the issue

**Closed by MaikuB** 2021-11-14 06:12 UTC
