### ISSUE TITLE
Crash on ios

### ISSUE THREAD

**Issue by nguyenhuutinh** [MaikuB/flutter_appauth#53] opened 2019-11-07 08:33 UTC
```
        0   CoreFoundation                      0x000000010d73202e __exceptionPreprocess + 350                     
        1   libobjc.A.dylib                     0x000000010d59fb20 objc_exception_throw + 48                       
        2   CoreFoundation                      0x000000010d7c4a71 _CFThrowFormattedException + 194                
        3   CoreFoundation                      0x000000010d7c3583 -[__NSArrayM insertObject:atIndex:].cold.1 + 35 
        4   CoreFoundation                      0x000000010d64515f -[__NSArrayM insertObject:atIndex:] + 1263      
        5   AppAuth                             0x0000000109b97382 -[OIDURLQueryComponent addParameter:value:] + 242
        6   AppAuth                             0x0000000109b797ca -[OIDAuthorizationRequest authorizationRequestURL] + 154
        7   AppAuth                             0x0000000109b79a3c -[OIDAuthorizationRequest externalUserAgentRequestURL] + 44
        8   AppAuth<…>                                                                                             
```

**Comment by nguyenhuutinh** [comment] 2019-11-07 08:33
in case url is not correct, app crash totally

**Comment by MaikuB** [comment] 2019-11-07 10:52
Not sure why an issue has been raised in this but this would be an expected behaviour since an exception would be raised. Keeping this behaviour would also provide more info on the native side. Closing this

**Closed by MaikuB** 2019-11-07 10:52 UTC
