### ISSUE TITLE
is there a way to close web view popup programmatically?

### ISSUE THREAD

**Issue by sohitEngg** [MaikuB/flutter_appauth#306] opened 2022-02-25 07:06 UTC
I have a requirement to close the login-popup without user interaction by programming, can you add a function, does it also make sense for you?
This is not even respecting  Navigator.popUntil() and remains on the screen, looks like overriding some app cycle behaviour too. Is there any workaround possible for now?

**Comment by MaikuB** [comment] 2022-03-08 08:47
The closing should already happen as part of the redirect and there's an example app in the repo that should show that it works. If  you find the example app doesn't work in your case then you may have a device with an old version of Android, in which case there's nothing much that can be done to my knowledge. If you find the example app is working and it's just an issue with your app then you'll need to check your app configuration. Either way the plugin is working as intended for this so I'll be closing the issue

**Closed by MaikuB** 2022-03-08 08:47 UTC
