### ISSUE TITLE
IOS redirect hangs after authenticating

### ISSUE THREAD

**Issue by bigDado** [MaikuB/flutter_appauth#304] opened 2022-02-23 07:55 UTC
Hello, I've seen a few posts mentioning this, adding a trailing slash etc. But I can't seem to get it working

my plist
```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
	         <string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>com.manager.app</string>
		</array>
	</dict>
</array>
```

my code 
```    
final result = await appAuth.authorizeAndExchangeCode(
      AuthorizationTokenRequest(
        clientId,
        redirectUri: "com.manager.app:/oauth_redirect",
        discoveryUrl: sso,
        scopes: scopes,
      ),
    );
```

I'm connecting to a .net IdentityServer4. Thanks for the help

**Comment by bigDado** [comment] 2022-02-24 13:18
First login when we enter email and password hangs in the redirect phase, and when we go back to the login page and click login => it succeeds without asking for any information, simply logs us in and continues normally.

**Comment by MaikuB** [comment] 2022-02-25 09:01
The trailing slash mentioned was only applicable for Azure AD and Azure B2C. Don't know why yours would hang when oAuth is generic and this is working with other providers including the demo identity server. You need to drill into the iOS side yourself using Xcode to debug to find out why the redirect isn't occurring

**Comment by MaikuB** [comment] 2022-10-08 05:54
Closing due to lack of updates from a while back. If you believe there's an issue then file a new issue and include a link to a repository hosting a minimal app that can reproduce the issue

**Closed by MaikuB** 2022-10-08 05:54 UTC

**Comment by dupuisdavid** [comment] 2025-05-07 16:19
Hello.

@bigDado. Did you find a solution? Is it working now? I am interested in your feedback!

**Comment by bigDado** [comment] 2025-05-08 09:23
@dupuisdavid hey, it's been a while :) I don't have access to that project anymore but I remember we figured it out. Don't remember how unfortunately
