### ISSUE TITLE
Flutter_appauth plugin is crashing

### ISSUE THREAD

**Issue by GadepalliAditya1998** [MaikuB/flutter_appauth#111] opened 2020-05-04 01:42 UTC
So I was trying to run in Samsung M20 Android 10 Device. 

When i call this method : _appAuth.authorizeAndExchangeCode, I get a Webview of my Login screen. But when i tap on my UI (TextField or Submit button) its crashing by closing the webview.

**Comment by GadepalliAditya1998** [comment] 2020-05-04 01:44
I can attach some of the Crash Logs in android Logcat


2020-05-04 07:12:21.133 22780-22780/? D/AndroidRuntime: Shutting down VM
    --------- beginning of crash
2020-05-04 07:12:21.134 22780-22780/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sec.android.app.sbrowser, PID: 22780
    java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:2078)
        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:2447)
        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1337)
        at org.chromium.content.browser.input.InputMethodManagerWrapper.isActive(InputMethodManagerWrapper.java:65)
        at org.chromium.content.browser.input.ThreadedInputConnectionFactory$1.run(ThreadedInputConnectionFactory.java:179)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7807)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)



java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
2020-05-04 07:12:21.140 22780-22780/? W/System.err:     at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:2078)
2020-05-04 07:12:21.140 22780-22780/? W/System.err:     at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:2447)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1337)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at org.chromium.content.browser.input.InputMethodManagerWrapper.isActive(InputMethodManagerWrapper.java:65)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at org.chromium.content.browser.input.ThreadedInputConnectionFactory$1.run(ThreadedInputConnectionFactory.java:179)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-05-04 07:12:21.141 3940-4043/? I/netd: firewallSetUidRule(2, 10114, 1) <8.01ms>
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7807)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-05-04 07:12:21.141 22780-22780/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by MaikuB** [comment] 2020-05-04 02:01
>  But when i tap on my UI (TextField or Submit button) its crashing by closing the webview.

What you've written there would indicate an issue to do with your app. I'm not sure how and why your app is allowing a button to be tapped either when the sign-in flow via the webview/Chrome custom tab needs to be complete first. If you're allowing this then this should be fixed in your app (e.g. disable buttons until the signing in is complete)

**Comment by GadepalliAditya1998** [comment] 2020-05-04 02:05
Hey MaikuB, the button that i referred in the issue indicates my Login Screen (WebPage) that is opened in the webview. When I try to fill the credentials its crashing

**Comment by MaikuB** [comment] 2020-05-04 02:07
There's an example app in this repo, can you download the app and see if you run into the same problem?

**Comment by MaikuB** [comment] 2020-05-04 02:08
Also note you need to download the repository or clone it for the example app to work

**Comment by GadepalliAditya1998** [comment] 2020-05-04 02:12
Hey I did it. I cloned your repo and when I try to signin using code exchange or no code exchange method, The webView appears and crashes. 

The app doesn't crash but the webview crash.

**Comment by MaikuB** [comment] 2020-05-04 02:22
You may need to help in fixing this issue then. I don't know what the cause of this is. Perhaps it's to do with using the Samsung browser for the webview and I don't have access to Samsung phones to look into this

**Comment by GadepalliAditya1998** [comment] 2020-05-04 02:24
Sure. I actually recorded the screen if you send me your mail Id I can forward it you. Is it fine?

**Comment by MaikuB** [comment] 2020-05-04 02:26
No, I'd rather not have attachments sent to my email and prefer it if it's something easily viewable online (e.g. convert to gif). I don't think the video will help much though

**Comment by GadepalliAditya1998** [comment] 2020-05-04 02:30
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51157467/80932505-574a5700-8ddd-11ea-9927-69c4b4347521.gif)

**Comment by MaikuB** [comment] 2020-05-04 02:46
Do you have Chrome on that phone? I would guess it's due to not having a supported browser installed

**Comment by GadepalliAditya1998** [comment] 2020-05-04 02:47
Yes chrome is installed on the phone and i saw its updated to the latest version.

**Comment by MaikuB** [comment] 2020-05-04 02:49
Not sure what's going on there then. Afraid you'll need to investigate this on your own

**Comment by a7me63azzab** [comment] 2020-05-06 14:51
Same issue here ... any solution please ??? 
`W/ActivityThread(12349): handleWindowVisibility: no activity for token android.os.BinderProxy@3cd4497
D/EGL_emulation(12349): eglMakeCurrent: 0xe2205ba0: ver 3 0 (tinfo 0xca5d7d70)
D/EGL_emulation(12349): eglMakeCurrent: 0xe2205ba0: ver 3 0 (tinfo 0xca5d7d70)
D/FlutterView(12349): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@9e23a3e
W/ActivityThread(12349): handleWindowVisibility: no activity for token android.os.BinderProxy@a7b2408
D/FlutterView(12349): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@9e23a3e
D/eglCodecCommon(12349): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(12349): eglCreateContext: 0xe422f660: maj 3 min 0 rcv 3
D/EGL_emulation(12349): eglMakeCurrent: 0xe422f660: ver 3 0 (tinfo 0xe42600c0)
D/EGL_emulation(12349): eglMakeCurrent: 0xe2205ba0: ver 3 0 (tinfo 0xca5d7d70)
D/AndroidRuntime(12349): Shutting down VM
E/AndroidRuntime(12349): FATAL EXCEPTION: main
E/AndroidRuntime(12349): Process: com.azzabaraby.callflowapp, PID: 12349
E/AndroidRuntime(12349): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65030, result=-1, data=Intent { dat=cf9742358564://oauth2redirect?state=3N1f421kehgUgidObDKqSA&session_state=8109092f-9ee0-4a9d-8a49-4bf3f00a2bfc&code=07e61262-c6ba-452f-8d46-5555bb063bb5.8109092f-9ee0-4a9d-8a49-4bf3f00a2bfc.df23130f-3b5e-4680-b726-9bb14f1e7b8d (has extras) }} to activity {com.azzabaraby.callflowapp/com.azzabaraby.callflowapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(12349): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime(12349): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime(12349): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(12349): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(12349): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(12349): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(12349): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12349): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12349): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(12349): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12349): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12349): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(12349): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(12349): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.finishWithResult(ContactsServicePlugin.java:239)
E/AndroidRuntime(12349): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:255)
E/AndroidRuntime(12349): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(12349): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(12349): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(12349): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)`

**Comment by MaikuB** [comment] 2020-05-06 21:49
@a7me63azzab please take a closer at the crash logs you posted as they don't relate to this plugin

**Comment by MaikuB** [comment] 2020-07-10 22:16
Closing this as i don't have enough info to reproduce this to fix. Not sure if this a device-specific or perhaps a setting on the phone is behind this issue

**Closed by MaikuB** 2020-07-10 22:16 UTC
