### ISSUE TITLE
Null data intent crash on Android

### ISSUE THREAD

**Issue by brianb-sf** [MaikuB/flutter_appauth#128] opened 2020-07-07 20:09 UTC
First off, thanks so much for this package. It is awesome and we really appreciate all the work that went into it.

## Description
- We are seeing a few crashes, mostly on Samsung devices around a null data intent in `onActivityResult` in `FlutterAppAuthPlugin.java`.
- Here is the line where the crash occurs https://github.com/MaikuB/flutter_appauth/blob/master/flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java#L372

## Other Info
- Have not been able to reproduce this and after googling around I saw that the react native app auth plugin was having a similar [issue](https://github.com/FormidableLabs/react-native-app-auth/pull/352) but following the steps to reproduce have not crashed the app in our testing.

## Questions
- Any ideas on how `onActivityResult` is being invoked with a null data intent in the first place? 
- Could we add a null on the intent check in `onActivityResult` to prevent the crash and just report the authorization attempt as an error?

**Comment by MaikuB** [comment] 2020-07-08 11:41
> First off, thanks so much for this package. It is awesome and we really appreciate all the work that went into it.

Thank you. Means a lot since I'd seen your team given a shout out before :)

> Any ideas on how onActivityResult is being invoked with a null data intent in the first place?

Afraid not. Seems like a weird thing to happen in the first place. Perhaps a device-specific issue.

> Could we add a null on the intent check in onActivityResult to prevent the crash and just report the authorization attempt as an error?

That sounds like a good idea, would you consider submitting a PR?

**Comment by brianb-sf** [comment] 2020-07-09 12:49
For sure, I can submit a PR to fix this! I just wanted to get your thoughts on the issue. Thanks again!

**Comment by gregertw** [comment] 2020-07-28 06:01
Hi,
I have included appauth in the first_app flutter starter app: https://github.com/gregertw/actingweb_firstapp

I have seen a few of the same exceptions reported by Crashlytics. Below is the stack trace from a Nexus 5X, 6.0.1. I have not seen it on Samsung.

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65030, result=0, data=null} to activity {io.actingweb.firstapp/io.actingweb.firstapp.MainActivity}: java.lang.NullPointerException: dataIntent must not be null
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3703)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3746)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by java.lang.NullPointerException: dataIntent must not be null
       at net.openid.appauth.p.a()
       at net.openid.appauth.f.a()
       at e.a.a.a.a()
       at e.c.b.e.a()
       at e.c.b.b.a()
       at e.c.b.a.onActivityResult()
       at android.app.Activity.dispatchActivityResult(Activity.java:6456)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3746)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by MaikuB** [comment] 2020-07-28 06:59
@gregertw it looks like @brianb-sf hasn't gotten around to submitting a PR. I'd suggest one yourself if you can though from the stack trace, it looks like it could be it comes from the Android AppAuth SDK itself. If so, not something that this plugin could fix as it's wrapper library

**Comment by gregertw** [comment] 2020-08-01 13:49
@brianb-sf do you have anything in the works? I'm not able to do this right away.

**Comment by li0nza** [comment] 2020-10-01 14:37
I have created a PR, I have not been able to test because I have not been able to reproduce the issue locally, but we do get crashes in our production environment.

https://github.com/MaikuB/flutter_appauth/pull/146

**Comment by MaikuB** [comment] 2020-10-11 07:55
Released a new version with the PR merged in so will close this

**Closed by MaikuB** 2020-10-11 07:55 UTC
