### ISSUE TITLE
Failed to authorize

### ISSUE THREAD

**Issue by markbeij** [MaikuB/flutter_appauth#203] opened 2021-04-15 06:03 UTC
Sometimes the app is unable to show the login screen. We see this in the logging as:
_PlatformException(authorize_and_exchange_code_failed, Failed to authorize: De bewerking kan niet worden voltooid. (org.openid.appauth.general fout -3.), null, null)_

This seems to be specific to iOS. The error code (-3) suggests that the user cancelled, but that doesn't seem to be the case. There is just no login screen. Is this a common problem? I'm not sure how to handle this better.

**Comment by markbeij** [comment] 2021-04-15 08:49
Most of the times this happens during startup I think. In main.dart we have code to ensure new push notification tokens are sent to our api. We're using bloc-pattern. `NotificationSettingsChangedEvent` triggers retrieving an access token and calling the API with that token.

```
_firebaseMessaging.onTokenRefresh.listen((event) async {
  //During startup it is likely that there is no currentContext just yet
  //By waiting just a tiny bit we are certain we don't miss any events
  while (GlobalVariable.navState.currentContext == null) {
    await Future.delayed(Duration(milliseconds: 50));
  }
  BlocProvider.of<ProfileBloc>(GlobalVariable.navState.currentContext).add(NotificationSettingsChangedEvent());
});
_firebaseMessaging.onIosSettingsRegistered.listen((event) async {
  //During startup it is likely that there is no currentContext just yet
  //By waiting just a tiny bit we are certain we don't miss any events
  while (GlobalVariable.navState.currentContext == null) {
    await Future.delayed(Duration(milliseconds: 50));
  }
  BlocProvider.of<ProfileBloc>(GlobalVariable.navState.currentContext).add(NotificationSettingsChangedEvent());
});
```

**Comment by MaikuB** [comment] 2021-04-15 13:50
I don't recall others reporting this nor do I know what the cause could be. Perhaps your app is doing this at certain points where it shouldn't do so but this is really just a guess

**Comment by markbeij** [comment] 2021-04-16 05:36
Thanks for your reply. Any suggestions what such point might be?

**Comment by MaikuB** [comment] 2021-04-23 23:49
Only what I mentioned before, which again was just a guess.  You'd need to debug to find out what's going on and may need to introduce more logging in your own app to help with that

**Comment by shubhamkatore** [comment] 2021-06-06 14:19
I am getting PlatformException(authorize_and_exchange_code_failed, null, null, null)
After upgrading to flutter 2.2.1

Code Block:
```
await _appAuth.authorizeAndExchangeCode(
              AuthorizationTokenRequest(
                configuration.clientId,
                configuration.redirectUrl,
                serviceConfiguration: _serviceConfiguration,
                scopes: configuration.scopes,
                preferEphemeralSession: preferEphemeralSession,
              ),
            );
```
Am I missing something, or is it platform specific?

@MaikuB

**Comment by Jemshi101** [comment] 2021-06-07 06:02
This is happening for me as well. But only getting reported in the crashlytics
![image](https://user-images.githubusercontent.com/8707635/120966593-0d703500-c784-11eb-9bbd-7673cb18a7db.png)

**Comment by MaikuB** [comment] 2021-06-27 05:00
These crash logs don't necessarily indicate an issue with the plugin and if there is an issue with the plugin, this would need a minimal app that can reproduce the problem. It may be possible that your app is initiating multiple requests at the same time. The code is publicly available as well so you could use that diagnose and debug

**Comment by MaikuB** [comment] 2022-10-08 05:45
Closing this as there's been no further info on how to reproduce this issue. If you can provide a way to reproduce this then please file a new issue and include a link to a repository hosting a minimal app that can reproduce the problem and include steps to reproduce as well

**Closed by MaikuB** 2022-10-08 05:45 UTC
